baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Wempy Tech Blog'
theme = "blist"

DefaultContentLanguage = "id"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.id]
    contentDir = "content/id" #Indonesian
    weight = 1
    languageName = "Indonesian"
    [languages.id.params]
      introTitle = "Hello World!"
      introSubtitle = "Welcome to the wempy tech blog, on this site you can find lots of tutorials and articles about programming."
      introPhoto = "/programmer.jpg"
    [[languages.id.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.id.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 2

    [[languages.id.menu.main]]
        name = "Projects"
        url = "page/projects/"
        weight = 3

    [[languages.id.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 4


[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Wempy.Tech · All rights reserved"
  favicon = "/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "Hello my name is Wempy Aditya, I am a beginner programmer who is learning."
  twitter = "https://twitter.com/Wempyaw"
  linkedin = "https://www.linkedin.com/in/wempy-aditya-0aa2721bb"
  github = "https://github.com/wempy-aditya"
  instagram = "https://www.instagram.com/wempyaw"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
